const DB_NAME="ExpenseTrackerV5";const STORES=["transactions","categories"];
let db,txs=[],cats=[],selectedDate=new Date();selectedDate.setDate(1);
const currencies=["CAD","USD","EUR","GBP","IRR"];
const defaults=[
{id:"home",name:"Home",icon:"🏠",type:"expense"},{id:"groceries",name:"Groceries",icon:"🛒",type:"expense"},{id:"car",name:"Car",icon:"🚗",type:"expense"},{id:"gas",name:"Gas",icon:"⛽️",type:"expense"},
{id:"restaurants",name:"Restaurants",icon:"🍽️",type:"expense"},{id:"loan",name:"Loan",icon:"🏦",type:"expense"},{id:"mortgage",name:"Mortgage",icon:"🏡",type:"expense"},{id:"insurance",name:"Insurance",icon:"🛡️",type:"expense"},
{id:"phone",name:"Phone & Internet",icon:"📱",type:"expense"},{id:"subscriptions",name:"Subscriptions",icon:"🔁",type:"expense"},{id:"health",name:"Health",icon:"🩺",type:"expense"},{id:"education",name:"Education",icon:"🎓",type:"expense"},
{id:"travel",name:"Travel",icon:"✈️",type:"expense"},{id:"childcare",name:"Childcare",icon:"🧸",type:"expense"},{id:"other-expense",name:"Other",icon:"📦",type:"expense"},
{id:"salary",name:"Salary",icon:"💼",type:"income"},{id:"bonus",name:"Bonus",icon:"🎁",type:"income"},{id:"refund",name:"Refund",icon:"↩️",type:"income"},{id:"other-income",name:"Other income",icon:"💵",type:"income"}];
const $=id=>document.getElementById(id);
const els={monthScroller:$("monthScroller"),summaryMonth:$("summaryMonth"),balance:$("balance"),incomeTotal:$("incomeTotal"),expenseTotal:$("expenseTotal"),yearChart:$("yearChart"),categoryList:$("categoryList"),transactionList:$("transactionList"),searchInput:$("searchInput"),currencyFilter:$("currencyFilter"),transactionDialog:$("transactionDialog"),transactionForm:$("transactionForm"),typeInput:$("typeInput"),amountInput:$("amountInput"),currencyInput:$("currencyInput"),categoryInput:$("categoryInput"),descriptionInput:$("descriptionInput"),dateInput:$("dateInput")};
function sget(){try{return JSON.parse(localStorage.getItem("expenseV5Settings"))||{};}catch{return{}}}function ssave(s){localStorage.setItem("expenseV5Settings",JSON.stringify(s))}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{for(const s of STORES)if(!r.result.objectStoreNames.contains(s))r.result.createObjectStore(s,{keyPath:"id"})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function getAll(store){return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,item){return new Promise((res,rej)=>{const r=db.transaction(store,"readwrite").objectStore(store).put(item);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function del(store,id){return new Promise((res,rej)=>{const r=db.transaction(store,"readwrite").objectStore(store).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function money(v,c){return new Intl.NumberFormat("en-CA",{style:"currency",currency:c}).format(v)}function monthKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}function currentCurrency(){return els.currencyFilter.value||"CAD"}function cat(id){return cats.find(c=>c.id===id)||{name:"Unknown",icon:"❓"}}
async function ensureCategories(){let list=await getAll("categories");const ids=new Set(list.map(c=>c.id));for(const c of defaults)if(!ids.has(c.id))await put("categories",c);list=await getAll("categories");if(!list.length)for(const c of defaults)await put("categories",c)}
async function refresh(){await ensureCategories();[txs,cats]=await Promise.all(STORES.map(getAll));render();updateCategoryOptions()}
function fillCurrencies(){for(const id of ["currencyFilter","currencyInput"])$(id).innerHTML=currencies.map(c=>`<option>${c}</option>`).join("");const s=sget();els.currencyFilter.value=s.currency||"CAD";els.currencyInput.value=s.currency||"CAD"}
function updateCategoryOptions(){const list=cats.filter(c=>c.type===els.typeInput.value);if(!list.length){$("categoryFallback").classList.remove("hidden");els.categoryInput.innerHTML=defaults.filter(c=>c.type===els.typeInput.value).map(c=>`<option value="${c.id}">${c.icon} ${c.name}</option>`).join("");setTimeout(()=>ensureCategories().then(refresh),0)}else{$("categoryFallback").classList.add("hidden");els.categoryInput.innerHTML=list.map(c=>`<option value="${c.id}">${c.icon} ${c.name}</option>`).join("")}}
function renderMonths(){els.monthScroller.innerHTML="";const y=selectedDate.getFullYear();for(let m=0;m<12;m++){const d=new Date(y,m,1),b=document.createElement("button");b.className="month-chip"+(m===selectedDate.getMonth()?" active":"");b.textContent=d.toLocaleDateString("en-CA",{month:"short"});b.onclick=()=>{selectedDate=d;render()};els.monthScroller.appendChild(b)}}
function monthTx(){const k=monthKey(selectedDate),c=currentCurrency();return txs.filter(t=>t.date.startsWith(k)&&t.currency===c)}
function renderSummary(){const a=monthTx(),c=currentCurrency(),inc=a.filter(t=>t.type==="income").reduce((s,t)=>s+Number(t.amount),0),exp=a.filter(t=>t.type==="expense").reduce((s,t)=>s+Number(t.amount),0),bal=inc-exp;els.summaryMonth.textContent=selectedDate.toLocaleDateString("en-CA",{month:"long",year:"numeric"})+" · "+c;els.balance.textContent=money(bal,c);els.balance.classList.toggle("positive",bal>=0);els.incomeTotal.textContent=money(inc,c);els.expenseTotal.textContent=money(exp,c)}
function renderYear(){const y=selectedDate.getFullYear(),c=currentCurrency(),vals=[];for(let m=0;m<12;m++){const k=`${y}-${String(m+1).padStart(2,"0")}`;vals.push(txs.filter(t=>t.type==="expense"&&t.currency===c&&t.date.startsWith(k)).reduce((s,t)=>s+Number(t.amount),0))}const max=Math.max(...vals,1);els.yearChart.innerHTML=vals.map((v,m)=>`<div class="chart-item"><div class="chart-track"><div class="chart-bar ${m===selectedDate.getMonth()?"activebar":""}" style="height:${Math.max(7,v/max*100)}%"></div></div><div class="chart-label">${new Date(y,m,1).toLocaleDateString("en-CA",{month:"narrow"})}</div></div>`).join("")}
function renderCategories(){const c=currentCurrency(),a=monthTx().filter(t=>t.type==="expense"),g={};a.forEach(t=>g[t.categoryId]=(g[t.categoryId]||0)+Number(t.amount));els.categoryList.innerHTML=Object.keys(g).length?Object.entries(g).sort((a,b)=>b[1]-a[1]).map(([id,v])=>{const x=cat(id);return `<div class="category-row"><div>${x.icon}</div><strong>${x.name}</strong><div class="amount">${money(v,c)}</div></div>`}).join(""):`<div class="empty">No expenses this month.</div>`}
function renderTransactions(){const q=els.searchInput.value.toLowerCase(),a=monthTx().filter(t=>!q||t.note.toLowerCase().includes(q)||cat(t.categoryId).name.toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date)),c=currentCurrency();els.transactionList.innerHTML=a.length?a.map(t=>`<div class="transaction-row"><div class="meta"><strong>${cat(t.categoryId).icon} ${t.note}</strong><span>${cat(t.categoryId).name} · ${t.date}</span></div><div class="amount">${t.type==="income"?"+":"−"}${money(Number(t.amount),c)}</div><button class="delete-btn no-export" data-id="${t.id}">×</button></div>`).join(""):`<div class="empty">No matching transactions.</div>`;els.transactionList.querySelectorAll("[data-id]").forEach(b=>b.onclick=async()=>{await deleteTransaction(b.dataset.id);await refresh()})}
function renderCustom(){const custom=cats.filter(c=>!defaults.some(d=>d.id===c.id));$("customCategoryList").innerHTML=custom.length?custom.map(c=>`<span class="custom-chip">${c.icon} ${c.name}</span>`).join(""):`<p class="muted">No custom categories yet.</p>`}
function render(){renderMonths();renderSummary();renderYear();renderCategories();renderTransactions();renderCustom()}

const cloud={url:"",key:"",accessToken:"",user:null,householdId:null};
function loadCloud(){const s=sget();cloud.url=s.supabaseUrl||"";cloud.key=s.supabaseAnonKey||"";cloud.accessToken=s.accessToken||"";cloud.householdId=s.householdId||null;$("supabaseUrl").value=cloud.url;$("supabaseAnonKey").value=cloud.key;updateCloudBanner()}
function headers(auth=true){const h={"apikey":cloud.key,"Content-Type":"application/json"};if(auth&&cloud.accessToken)h.Authorization="Bearer "+cloud.accessToken;return h}
async function rest(path,opts={}){if(!cloud.url||!cloud.key)throw new Error("Cloud configuration is missing.");const r=await fetch(`${cloud.url}/rest/v1/${path}`,{...opts,headers:{...headers(true),...(opts.headers||{})}});if(!r.ok)throw new Error(await r.text());const text=await r.text();return text?JSON.parse(text):null}
async function auth(path,body){if(!cloud.url||!cloud.key)throw new Error("Save your Supabase URL and public key first.");const r=await fetch(`${cloud.url}/auth/v1/${path}`,{method:"POST",headers:headers(false),body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.msg||d.error_description||d.message||"Authentication failed");return d}
function updateCloudBanner(){if(cloud.accessToken&&cloud.householdId){$("cloudStatusTitle").textContent="Shared sync on";$("cloudStatusText").textContent="This household can sync between both phones."; $("cloudSetupBtn").textContent="Sync settings"}else{$("cloudStatusTitle").textContent="Local mode";$("cloudStatusText").textContent="Set up shared sync so both phones use the same household data."; $("cloudSetupBtn").textContent="Set up sync"}}
async function getUser(){if(!cloud.accessToken)return;const r=await fetch(`${cloud.url}/auth/v1/user`,{headers:headers(true)});if(r.ok)cloud.user=await r.json()}
async function syncFromCloud(){if(!cloud.accessToken||!cloud.householdId)return;const rc=await rest(`categories?household_id=eq.${cloud.householdId}&select=*`),rt=await rest(`transactions?household_id=eq.${cloud.householdId}&select=*`);for(const c of rc||[])await put("categories",{id:c.id,name:c.name,icon:c.icon,type:c.type});for(const t of rt||[])await put("transactions",{id:t.id,type:t.type,amount:Number(t.amount),currency:t.currency,categoryId:t.category_id,note:t.note,date:t.date});await refresh();$("authMessage").textContent="Synced."}
async function pushCategory(c){if(!cloud.accessToken||!cloud.householdId)return;await rest("categories",{method:"POST",headers:{"Prefer":"resolution=merge-duplicates"},body:JSON.stringify({id:c.id,household_id:cloud.householdId,name:c.name,icon:c.icon,type:c.type})})}
async function pushTransaction(t){if(!cloud.accessToken||!cloud.householdId)return;await rest("transactions",{method:"POST",headers:{"Prefer":"resolution=merge-duplicates"},body:JSON.stringify({id:t.id,household_id:cloud.householdId,type:t.type,amount:t.amount,currency:t.currency,category_id:t.categoryId,note:t.note,date:t.date})})}
async function deleteTransaction(id){await del("transactions",id);if(cloud.accessToken&&cloud.householdId)try{await rest(`transactions?id=eq.${id}`,{method:"DELETE"})}catch{}}
async function uploadAllLocal(){for(const c of cats)await pushCategory(c);for(const t of txs)await pushTransaction(t)}
async function signIn(){const d=await auth("token?grant_type=password",{email:$("authEmail").value,password:$("authPassword").value});cloud.accessToken=d.access_token;cloud.user=d.user;const s=sget();s.accessToken=d.access_token;ssave(s);$("authMessage").textContent="Signed in.";updateCloudBanner();if(cloud.householdId)await syncFromCloud()}
async function signUp(){const d=await auth("signup",{email:$("authEmail").value,password:$("authPassword").value});$("authMessage").textContent=d.access_token?"Account created and signed in.":"Account created. Check your email if confirmation is enabled.";if(d.access_token){cloud.accessToken=d.access_token;cloud.user=d.user;const s=sget();s.accessToken=d.access_token;ssave(s);updateCloudBanner()}}
async function createHousehold(){if(!cloud.user)await getUser();if(!cloud.user)throw new Error("Sign in first.");const name=$("householdName").value.trim();if(!name)throw new Error("Enter a household name.");const code=Math.random().toString(36).slice(2,8).toUpperCase();const rows=await rest("households",{method:"POST",headers:{"Prefer":"return=representation"},body:JSON.stringify({name,join_code:code,created_by:cloud.user.id})});const h=rows[0];await rest("household_members",{method:"POST",body:JSON.stringify({household_id:h.id,user_id:cloud.user.id})});cloud.householdId=h.id;const s=sget();s.householdId=h.id;ssave(s);$("householdMessage").textContent=`Created. Your wife's join code is: ${code}`;updateCloudBanner();await uploadAllLocal()}
async function joinHousehold(){if(!cloud.user)await getUser();if(!cloud.user)throw new Error("Sign in first.");const code=$("joinCodeInput").value.trim().toUpperCase();const hs=await rest(`households?join_code=eq.${code}&select=*`);if(!hs.length)throw new Error("Code not found.");const h=hs[0];await rest("household_members",{method:"POST",headers:{"Prefer":"resolution=merge-duplicates"},body:JSON.stringify({household_id:h.id,user_id:cloud.user.id})});cloud.householdId=h.id;const s=sget();s.householdId=h.id;ssave(s);$("householdMessage").textContent=`Joined ${h.name}.`;updateCloudBanner();await syncFromCloud()}

function excelRows(){return txs.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(t=>({Date:t.date,Type:t.type,Amount:Number(t.amount),Currency:t.currency,Category:cat(t.categoryId).name,Description:t.note}))}
function exportExcel(){
  if(typeof XLSX==="undefined"){return $("exportMessage").textContent="Excel library did not load. Check internet and try again."}
  const wb=XLSX.utils.book_new();
  const txSheet=XLSX.utils.json_to_sheet(excelRows());
  XLSX.utils.book_append_sheet(wb,txSheet,"Transactions");
  const catRows=cats.map(c=>({Type:c.type,Category:c.name,Icon:c.icon}));
  XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(catRows),"Categories");
  const monthly=[];
  for(const currency of currencies){
    const years=[...new Set(txs.filter(t=>t.currency===currency).map(t=>t.date.slice(0,4)))].sort();
    for(const y of years)for(let m=1;m<=12;m++){const k=`${y}-${String(m).padStart(2,"0")}`,a=txs.filter(t=>t.currency===currency&&t.date.startsWith(k));monthly.push({Month:k,Currency:currency,Income:a.filter(t=>t.type==="income").reduce((s,t)=>s+Number(t.amount),0),Expenses:a.filter(t=>t.type==="expense").reduce((s,t)=>s+Number(t.amount),0)})}
  }
  XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(monthly),"Monthly Summary");
  const breakdown=[];
  for(const currency of currencies)for(const c of cats.filter(x=>x.type==="expense")){const total=txs.filter(t=>t.currency===currency&&t.type==="expense"&&t.categoryId===c.id).reduce((s,t)=>s+Number(t.amount),0);if(total)breakdown.push({Currency:currency,Category:c.name,Total:total})}
  XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(breakdown),"Category Summary");
  XLSX.writeFile(wb,`expense-tracker-${new Date().toISOString().slice(0,10)}.xlsx`);
  $("exportMessage").textContent="Excel file created.";
}
async function exportPdf(){
  if(typeof html2canvas==="undefined"||!window.jspdf){return $("exportMessage").textContent="PDF libraries did not load. Check internet and try again."}
  $("exportMessage").textContent="Building PDF…";
  const area=$("reportArea"),canvas=await html2canvas(area,{scale:2,backgroundColor:"#f4f6f5",useCORS:true});
  const img=canvas.toDataURL("image/jpeg",0.92),{jsPDF}=window.jspdf,pdf=new jsPDF("p","mm","a4");
  const pageW=210,pageH=297,margin=8,imgW=pageW-2*margin,imgH=canvas.height*imgW/canvas.width;
  let y=margin,remaining=imgH;
  pdf.addImage(img,"JPEG",margin,y,imgW,imgH);
  remaining-=pageH-2*margin;
  while(remaining>0){pdf.addPage();y=margin- (imgH-remaining);pdf.addImage(img,"JPEG",margin,y,imgW,imgH);remaining-=pageH-2*margin}
  pdf.save(`expense-report-${new Date().toISOString().slice(0,10)}.pdf`);
  $("exportMessage").textContent="PDF created with the dashboard, chart, categories, and transactions.";
}
function exportCsv(){const rows=[["Date","Type","Amount","Currency","Category","Description"],...excelRows().map(x=>[x.Date,x.Type,x.Amount,x.Currency,x.Category,x.Description])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="expenses.csv";a.click();URL.revokeObjectURL(a.href)}

$("addBtn").onclick=async()=>{await ensureCategories();cats=await getAll("categories");els.transactionForm.reset();els.typeInput.value="expense";updateCategoryOptions();els.currencyInput.value=currentCurrency();els.dateInput.value=new Date().toISOString().slice(0,10);els.transactionDialog.showModal()}
$("closeTransactionDialog").onclick=()=>els.transactionDialog.close();els.typeInput.onchange=updateCategoryOptions;els.searchInput.oninput=renderTransactions;els.currencyFilter.onchange=()=>{const s=sget();s.currency=currentCurrency();ssave(s);render()}
$("prevMonth").onclick=()=>{selectedDate=new Date(selectedDate.getFullYear(),selectedDate.getMonth()-1,1);render()};$("nextMonth").onclick=()=>{selectedDate=new Date(selectedDate.getFullYear(),selectedDate.getMonth()+1,1);render()}
els.transactionForm.onsubmit=async e=>{e.preventDefault();const t={id:crypto.randomUUID(),type:els.typeInput.value,amount:Number(els.amountInput.value),currency:els.currencyInput.value,categoryId:els.categoryInput.value,note:els.descriptionInput.value.trim(),date:els.dateInput.value};await put("transactions",t);await pushTransaction(t);els.transactionDialog.close();await refresh()}
$("manageBtn").onclick=()=>$("manageDialog").showModal();$("closeManageDialog").onclick=()=>$("manageDialog").close()
$("addCategoryBtn").onclick=async()=>{const name=$("categoryNameInput").value.trim();if(!name)return;const c={id:crypto.randomUUID(),name,icon:$("categoryIconInput").value.trim()||"📌",type:$("categoryTypeInput").value};await put("categories",c);await pushCategory(c);$("categoryNameInput").value="";await refresh()}
$("settingsBtn").onclick=()=>$("settingsDialog").showModal();$("cloudSetupBtn").onclick=()=>$("settingsDialog").showModal();$("closeSettingsDialog").onclick=()=>$("settingsDialog").close()
$("saveCloudConfigBtn").onclick=()=>{const s=sget();s.supabaseUrl=$("supabaseUrl").value.trim().replace(/\/$/,"");s.supabaseAnonKey=$("supabaseAnonKey").value.trim();ssave(s);loadCloud();$("authMessage").textContent="Saved."}
$("signInBtn").onclick=()=>signIn().catch(e=>$("authMessage").textContent=e.message);$("signUpBtn").onclick=()=>signUp().catch(e=>$("authMessage").textContent=e.message);$("signOutBtn").onclick=()=>{const s=sget();delete s.accessToken;delete s.householdId;ssave(s);cloud.accessToken="";cloud.householdId=null;cloud.user=null;updateCloudBanner();$("authMessage").textContent="Signed out."}
$("createHouseholdBtn").onclick=()=>createHousehold().catch(e=>$("householdMessage").textContent=e.message);$("joinHouseholdBtn").onclick=()=>joinHousehold().catch(e=>$("householdMessage").textContent=e.message)
$("syncBtn").onclick=()=>syncFromCloud().catch(e=>$("cloudStatusText").textContent="Sync failed: "+e.message)
$("exportBtn").onclick=()=>$("exportDialog").showModal();$("closeExportDialog").onclick=()=>$("exportDialog").close();$("exportExcelBtn").onclick=exportExcel;$("exportPdfBtn").onclick=exportPdf;$("exportCsvBtn").onclick=exportCsv;
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(()=>{}));
(async()=>{db=await openDB();await ensureCategories();fillCurrencies();loadCloud();await getUser();await refresh();if(cloud.accessToken&&cloud.householdId)syncFromCloud().catch(()=>{})})()